# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ea746f0bef56b287ba1e7e95b4054026021ffe5bf55271d5cf0a135bbdcaa462be8fbf31ad681d3ab43d063fe0b5c869c1b8126b222b93836d2b4750060008f

test:
  secret_key_base: 1505923925d096db049d3984859838cdc28cbf5a8be33682e974bd83b396caf63f55c5e3d8a04a0d7becda67fd6d87f1df307dfee0e81b9baead9bfb91c50a24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
